version: "3.8"

services:
  db:
    image: mysql:8
    container_name: discord-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - discord-net

  redis:
    image: redis:7.2-alpine
    container_name: discord-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    networks:
      - discord-net

  app:
    image: lwonbin/discord-server:latest
    container_name: discord-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    networks:
      - discord-net


networks:
  discord-net:
