spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: discord-redis.wpvzfq.ng.0001.apn2.cache.amazonaws.com
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://developing.cfauuwy0urbj.ap-northeast-2.rds.amazonaws.com:3306/developing
    username: root
    password: dnjsqls00!!

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        sql: warn
        type:
          descriptor:
            sql:
              BasicBinder: warn
    root: info

server:
  port: 8080